using DfE.FindInformationAcademiesTrusts.Data.Enums;
using DfE.FindInformationAcademiesTrusts.Data.FiatDb.Models;
using Microsoft.EntityFrameworkCore;

namespace DfE.FindInformationAcademiesTrusts.Data.FiatDb.UnitTests.Contexts;

public class SchoolContactEntityConfigurationTests(FiatDbContainerFixture fiatDbContainerFixture)
    : BaseFiatDbTest(fiatDbContainerFixture)
{
    [Fact]
    public void Contacts_should_have_autogenerated_id_column()
    {
        FiatDbContext.SchoolContacts.AddRange(
            new SchoolContact
            {
                Name = "My RegionsGroupLocalAuthorityLead",
                Email = "my.RegionsGroupLocalAuthorityLead@education.gov.uk",
                Urn = 101234,
                Role = SchoolContactRole.RegionsGroupLocalAuthorityLead
            },
            new SchoolContact
            {
                Name = "My RegionsGroupLocalAuthorityLead2",
                Email = "my.RegionsGroupLocalAuthorityLead2@education.gov.uk",
                Urn = 102345,
                Role = SchoolContactRole.RegionsGroupLocalAuthorityLead
            },
            new SchoolContact
            {
                Name = "My RegionsGroupLocalAuthorityLead3",
                Email = "my.RegionsGroupLocalAuthorityLead2@education.gov.uk",
                Urn = 103567,
                Role = SchoolContactRole.RegionsGroupLocalAuthorityLead
            });

        FiatDbContext.SaveChanges();

        FiatDbContext.SchoolContacts.Select(c => c.Id).Should().OnlyHaveUniqueItems();
    }

    [Fact]
    public void Contacts_should_have_autogenerated_last_modified_column()
    {
        var entry = FiatDbContext.SchoolContacts.Add(new SchoolContact
        {
            Name = "My RegionsGroupLocalAuthorityLead",
            Email = "my.RegionsGroupLocalAuthorityLead@education.gov.uk",
            Urn = 101234,
            Role = SchoolContactRole.RegionsGroupLocalAuthorityLead
        }).Entity;

        FiatDbContext.SaveChanges();

        entry.LastModifiedAtTime.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
    }

    [Fact]
    public void Contacts_should_have_unique_uid_role_combinations()
    {
        FiatDbContext.SchoolContacts.Add(new SchoolContact
        {
            Name = "My RegionsGroupLocalAuthorityLead",
            Email = "my.RegionsGroupLocalAuthorityLead@education.gov.uk",
            Urn = 101234,
            Role = SchoolContactRole.RegionsGroupLocalAuthorityLead
        });
        FiatDbContext.SchoolContacts.Add(new SchoolContact
        {
            Name = "other RegionsGroupLocalAuthorityLead",
            Email = "other.RegionsGroupLocalAuthorityLead@education.gov.uk",
            Urn = 101234,
            Role = SchoolContactRole.RegionsGroupLocalAuthorityLead
        });

        var action = () => FiatDbContext.SaveChanges();

        action.Should().Throw<DbUpdateException>();
    }

    [Fact]
    public async Task Contacts_should_retain_history_of_changes()
    {
        var entry = FiatDbContext.SchoolContacts.Add(new SchoolContact
        {
            Name = "original name",
            Email = "original.email@education.gov.uk",
            Urn = 101234,
            Role = SchoolContactRole.RegionsGroupLocalAuthorityLead
        }).Entity;

        await FiatDbContext.SaveChangesAsync();

        // ensure that some time has passed before updating the entity because the temporal table will overwrite entries
        // with the same timestamp, causing this test to be flaky
        await Task.Delay(10);

        entry.Name = "new name";

        await FiatDbContext.SaveChangesAsync();
        await Task.Delay(10);

        entry.Email = "new.email@education.gov.uk";

        await FiatDbContext.SaveChangesAsync();
        await Task.Delay(10);

        var allVersions = await FiatDbContext.SchoolContacts.TemporalAll().Where(c => c.Urn == 101234).ToArrayAsync();

        allVersions.Should().Satisfy(
            [
                contact => contact.Name == "original name" && contact.Email == "original.email@education.gov.uk",
                contact => contact.Name == "new name" && contact.Email == "original.email@education.gov.uk",
                contact => contact.Name == "new name" && contact.Email == "new.email@education.gov.uk"
            ]
            , $"there should be three versions of the history in {string.Join(", ", allVersions.Select(c => $"[{c.Name}, {c.Email}, {c.LastModifiedAtTime:O}]"))}");
    }
}
