using System.Diagnostics.CodeAnalysis;

namespace DfE.FindInformationAcademiesTrusts.Data.AcademiesDb.Models.Sharepoint;

[ExcludeFromCodeCoverage] // Database model POCO generated by EF scaffold
public class SharepointTrustDocLink
{
    public string FolderPrefix { get; set; } = null!;

    public string FolderYear { get; set; } = null!;

    public string DocumentFilename { get; set; } = null!;

    public string? DocumentLink { get; set; }

    public string? DocumentIdvalue { get; set; }

    public string? ContentType { get; set; }

    public string? DocumentPath { get; set; }

    public DateTime? CreatedDateTime { get; set; }

    public DateTime? ModifiedDateTime { get; set; }

    public DateTime DataRefreshDateTime { get; set; }

    public string? CompaniesHouseNumber { get; set; }

    public string? TrustRefNumber { get; set; }
}
