using DfE.FindInformationAcademiesTrusts.Data.AcademiesDb.Faker.Helpers;

namespace DfE.FindInformationAcademiesTrusts.Data.AcademiesDb.Faker;

public static class Data
{
    /// <summary>
    ///     Trust names have been generated by Chat GPT AI and are fictional.
    ///     Any resemblance to real Trusts is entirely unintentional. If you spot a
    ///     real name then please raise a PR to correct it to a fake one
    /// </summary>
    public static TrustToGenerate[] TrustsToGenerate { get; } =
    {
        new("ABBEY LANE ACADEMIES TRUST"),
        new("EDIFY MULTI-ACADEMY TRUST"),
        new("INNOVATE ACADEMY TRUST"),
        new("MOMENTUM MULTI-ACADEMY TRUST"),
        new("VANGUARD LEARNING TRUST"),
        new("PROGRESSIVE EDUCATION TRUST"),
        new("HORIZON MULTI-ACADEMY TRUST"),
        new("ELEVATE SCHOOLS TRUST"),
        new("VISIONARY ACADEMY TRUST"),
        new("EMPOWERMENT MULTI-ACADEMY TRUST"),
        new("ECHELON EDUCATION TRUST"),
        new("ASCENDANCY ACADEMY TRUST"),
        new("NEXUS MULTI-ACADEMY TRUST"),
        new("MERIT ACADEMY TRUST"),
        new("EPIC LEARNING TRUST"),
        new("PEAK MULTI-ACADEMY TRUST"),
        new("LEGACY EDUCATION TRUST"),
        new("ACCLIVITY MULTI-ACADEMY TRUST"),
        new("PINNACLE EDUCATION TRUST"),
        new("THRIVE MULTI-ACADEMY TRUST"),
        new("ELEVATED SCHOOLS TRUST"),
        new("CHAMPION ACADEMY TRUST"),
        new("INTREPID EDUCATION TRUST"),
        new("PROSPECT MULTI-ACADEMY TRUST"),
        new("NEW HORIZONS TRUST"),
        new("MILESTONE MULTI-ACADEMY TRUST"),
        new("GALVANIZE ACADEMY TRUST"),
        new("CORNERSTONE MULTI-ACADEMY TRUST"),
        new("INSPIRE MULTI-ACADEMY TRUST"),
        new("SUCCESS MULTI-ACADEMY TRUST"),
        new("BRIDGE EDUCATION TRUST"),
        new("CRESCENDO ACADEMY TRUST"),
        new("POTENTIAL LEARNING TRUST"),
        new("HORIZONS MULTI-ACADEMY TRUST"),
        new("RISE EDUCATION TRUST"),
        new("EXCEL MULTI-ACADEMY TRUST"),
        new("UNITY LEARNING TRUST"),
        new("ADEPT ACADEMY TRUST"),
        new("EXCELLENCE MULTI-ACADEMY TRUST"),
        new("PROSPERITY EDUCATION TRUST"),
        new("PATHFINDER MULTI-ACADEMY TRUST"),
        new("VITALITY ACADEMY TRUST"),
        new("FORWARD MULTI-ACADEMY TRUST"),
        new("TRANSCENDENCE EDUCATION TRUST"),
        new("ADVANTAGE ACADEMY TRUST"),
        new("ILLUMINATE MULTI-ACADEMY TRUST"),
        new("FUSION EDUCATION TRUST"),
        new("EMPOWER ACADEMY TRUST"),
        new("ILLUMINATE LEARNING TRUST"),
        new("CHALLENGER MULTI-ACADEMY TRUST"),
        new("ST MARY'S ACADEMY TRUST", "Single-academy trust", schools: "St. Mary's Academy"),
        new("ST MARY'S ANGLICAN ACADEMY", "Single-academy trust", schools: "St. Mary's Anglican Academy"),
        new("ST MARY'S CATHOLIC HIGH SCHOOL ACADEMY TRUST", "Single-academy trust",
            schools: "St. Mary's Catholic High School Academy"),
        new("ST MARY'S CATHOLIC PRIMARY SCHOOL", "Single-academy trust", schools: "St. Mary's Catholic Primary School"),
        new("ST MARY'S CATHOLIC PRIMARY SCHOOL (ACADEMY TRUST), SWINDON",
            "Single-academy trust", schools: "St. Mary's Catholic Primary School"),
        new("ST MARY'S CATHOLIC PRIMARY SCHOOL (HERRINGTHORPE), A CATHOLIC VOLUNTARY ACADEMY",
            "Single-academy trust", schools: "St. Mary's Catholic Primary School"),
        new("ST MARY'S CATHOLIC PRIMARY SCHOOL (MALTBY)", "Single-academy trust",
            schools: "St. Mary's Catholic Primary School"),
        new("ST MARY'S CATHOLIC PRIMARY SCHOOL, CHURCHDOWN", "Single-academy trust",
            schools: "St. Mary's Catholic Primary School"),
        new("ST MARY'S CATHOLIC PRIMARY SCHOOLS TRUST", "Multi-academy trust", false, "Open",
            "St Mary's Catholic Primary School", "St. Mary's Catholic Primary School",
            "St. Marys Catholic Primary School", "St. Mary's Catholic Primary School",
            "St Marys Catholic Primary School", "St. Mary's Catholic Primary School", "St. Mary's RC Primary School",
            "St. Mary's Primary School", "St. Mary's Primary School"),
        new("ST MARY'S CE ACADEMY, CHESHUNT", "Single-academy trust", schools: "St Mary's CE Academy"),
        new("ST MARY'S CHURCH OF ENGLAND ACADEMY TRUST", "Single-academy trust",
            schools: "St Mary's Church of England Academy"),
        new("ST MARY'S CHURCH OF ENGLAND ACADEMY, STOTFOLD", "Single-academy trust", schools: "St Mary's Cofe Academy"),
        new("ST MARY'S CHURCH OF ENGLAND JUNIOR SCHOOL", "Single-academy trust", schools: "St Mary's C.E. Academy"),
        new("ST MARY'S CHURCH OF ENGLAND PRIMARY ACADEMY, DILWYN", "Single-academy trust",
            schools: "St Mary's C/E Academy"),
        new("ST MARY'S CHURCH OF ENGLAND SCHOOL, NORWOOD GREEN", "Single-academy trust",
            schools: "St Mary's C of E Academy"),
        new("ST MARY'S CHURCH OF ENGLAND VA PRIMARY ACADEMY", "Single-academy trust",
            schools: "St Mary's Church of England VA Primary Academy"),
        new("ST MARY'S PRIMARY SCHOOL, A CATHOLIC VOLUNTARY ACADEMY",
            "Single-academy trust", schools: "St Mary's Primary School, A Catholic Voluntary Academy"),
        new("THE DIOCESE OF CANTERBURY ACADEMIES TRUST"),
        new("THE DIOCESE OF CHELMSFORD VINE SCHOOLS TRUST"),
        new("THE DIOCESE OF COVENTRY MULTI-ACADEMY TRUST"),
        new("THE DIOCESE OF ELY MULTI-ACADEMY TRUST"),
        new("THE DIOCESE OF GLOUCESTER ACADEMIES TRUST"),
        new("THE DIOCESE OF NORWICH EDUCATION AND ACADEMIES TRUST"),
        new("THE DIOCESE OF NORWICH ST BENET'S MULTI-ACADEMY TRUST"),
        new("THE DIOCESE OF SHEFFIELD ACADEMIES TRUST"),
        new("THE DIOCESE OF WESTMINSTER ACADEMY TRUST"),
        new("THE DIOCESE OF WORCESTER MULTI ACADEMY TRUST", hasNoAcademies: true, status: "Closed"),
        new("SHEFFIELD SOUTH EAST TRUST", hasNoAcademies: true),
        new("CANTERBURY CROSS EDUCATION TRUST", "Single-academy trust", true, "Closed"),
        new("WESTMINSTER ACADEMY TRUST", "Single-academy trust", true, "Open")
    };

    public static string?[] Regions { get; } =
    {
        "London",
        null,
        "East of England",
        "South East",
        "West Midlands",
        "North West",
        "North East",
        "East Midlands",
        "Yorkshire and the Humber",
        "South West"
    };

    public static string[] LocalAuthorities { get; } =
    {
        "Barnsley",
        "Bradford",
        "Calderdale",
        "Doncaster",
        "East Riding of Yorkshire",
        "Kingston upon Hull, City of",
        "Kirklees",
        "Leeds",
        "North East Lincolnshire",
        "North Lincolnshire",
        "North Yorkshire",
        "Rotherham",
        "Sheffield",
        "Wakefield",
        "York"
    };

    public static Dictionary<string, string[]> GovernorAppointingBodies { get; } = new()
    {
        {
            "Accounting Officer", new[]
            {
                "N/A"
            }
        },
        {
            "Chair of Trustees", new[]
            {
                "Any additional members appointed by the members of the academy trust",
                "Appointed by academy members",
                "Appointed by foundation/Trust",
                "Appointed by GB/board",
                "Appointed by Regional Schools Commissioner (RSC)",
                "Appointed by trustees",
                "Elected by parents",
                "Ex-officio by virtue of office as headteacher/principal",
                "Ex-officio foundation governor (appointed by foundation by virtue of the office they hold)",
                "Foundation/sponsor members",
                "Interim Executive Board",
                "N/A",
                "Nominated by other body and appointed by GB",
                "Original (signatory) members",
                "Persons who are appointed by the foundation body or sponsor (if applicable)"
            }
        },
        {
            "Chief Financial Officer", new[]
            {
                "N/A"
            }
        },
        {
            "Member", new[]
            {
                "Any additional members appointed by the members of the academy trust",
                "Appointed by academy members",
                "Appointed by foundation/Trust",
                "Appointed by GB/board",
                "Appointed by Regional Schools Commissioner (RSC)",
                "Elected by parents",
                "Elected by school staff",
                "Ex-officio by virtue of office as headteacher/principal",
                "Ex-officio foundation governor (appointed by foundation by virtue of the office they hold)",
                "Foundation/sponsor members",
                "Interim Executive Board",
                "N/A",
                "Nominated by other body and appointed by GB",
                "Original (signatory) members",
                "Parent appointed by GB/board due to no election candidates",
                "Persons who are appointed by the foundation body or sponsor (if applicable)"
            }
        },
        {
            "Trustee", new[]
            {
                "Any additional members appointed by the members of the academy trust",
                "Appointed by academy members",
                "Appointed by foundation/Trust",
                "Appointed by GB/board",
                "Appointed by LA",
                "Appointed by Regional Schools Commissioner (RSC)",
                "Appointed by trustees",
                "Elected by parents",
                "Elected by school staff",
                "Ex-officio by virtue of office as headteacher/principal",
                "Ex-officio foundation governor (appointed by foundation by virtue of the office they hold)",
                "Foundation/sponsor members",
                "Interim Executive Board",
                "N/A",
                "Nominated by LA and appointed by GB",
                "Nominated by other body and appointed by GB",
                "Original (signatory) members",
                "Parent appointed by GB/board due to no election candidates",
                "Persons who are appointed by the foundation body or sponsor (if applicable)"
            }
        }
    };

    public static string[] Schools { get; } =
    {
        "St. Mary's",
        "St. Marys",
        "St. John's",
        "St. Peter's",
        "St. Joseph's",
        "St. Paul's",
        "St. James'",
        "St. James's",
        "St. Anne's",
        "St. Catherine's",
        "Momentum Community",
        "Barr and Community",
        "Beacon",
        "Co-op",
        "George Abbey",
        "Glyn",
        "Greensward",
        "Halewood",
        "Harris",
        "Holly Lodge Girls'",
        "Lampton",
        "Limehurst",
        "Longhill",
        "Malbank",
        "Meridian",
        "Mulberry",
        "Northwood",
        "Oasis",
        "Horizon",
        "Peacehaven Community",
        "Queen Elizabeth's",
        "Queensbridge"
    };
}
