version: "3.8"
name: fiat-fake-db-only
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: mySuperStrong_pa55word!!!
    ports:
      - "1435:1433"
    networks:
      - test-ci
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "mySuperStrong_pa55word!!!"
      interval: "2s"
      retries: 10
    restart: always
  import-sql:
    image: mcr.microsoft.com/mssql-tools:latest
    command: |
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "mySuperStrong_pa55word!!!" -d master -i /data/createScript.sql
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "mySuperStrong_pa55word!!!" -i /data/insertScript.sql
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - test-ci
    volumes:
      - ../tests/DFE.FindInformationAcademiesTrusts.CypressTests/data:/data

networks:
  test-ci:
