version: "3.8"
services:
  wiremock:
    image: wiremock/wiremock:latest-alpine
    ports:
      - 8443:8443/tcp
    networks:
      - test-ci
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet DfE.FindInformationAcademiesTrusts.dll"
    ports:
      - 80:80/tcp
    networks:
      - test-ci
    environment:
      - ASPNETCORE_ENVIRONMENT="CI"
      - AcademiesApi__Endpoint="https://wiremock:8443"
      - AcademiesApi__Key="00000000-0000-0000-000-000000000000"

networks:
  test-ci:
