version: "3.8"
services:
  faker:
    build:
      context: ..
      dockerfile: docker/AcademiesDbFaker.Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mySuperStrong_pa55word!!!
