version: "3.8"
services:
  faker:
    build:
      context: ..
      dockerfile: docker/AcademiesDbFaker.Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mySuperStrong_pa55word!!!
    networks:
      - test-ci
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet DfE.FindInformationAcademiesTrusts.dll"
    ports:
      - 80:80/tcp
    networks:
      - test-ci
    environment:
      - ASPNETCORE_ENVIRONMENT=CI
      - TestOverride__PlaywrightTestSecret=TestSuperSecret
      - ConnectionStrings__AcademiesDb=Server=localhost;User Id=sa;Password=mySuperStrong_pa55word!!!;TrustServerCertificate=true

networks:
  test-ci:
