name: fiat-fake-db-only
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: mySuperStrong_pa55word!!!
    ports:
      - "1435:1433"
    networks:
      - test-ci
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "mySuperStrong_pa55word!!!" -C
      interval: "2s"
      retries: 10
  import-sql:
    image: mcr.microsoft.com/mssql-tools:latest
    command: >
      sh -c "/opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "mySuperStrong_pa55word!!!" -d master -i /data/createScript.sql -C &&
             /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "mySuperStrong_pa55word!!!" -d sip -i /data/insertScript.sql -C &&
             /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P "mySuperStrong_pa55word!!!" -d master -Q \"CREATE DATABASE fiat\" -C"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - test-ci
    volumes:
      - ../tests/DFE.FindInformationAcademiesTrusts.CypressTests/data:/data

networks:
  test-ci:
