version: "3.8"
name: fiat
services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet DfE.FindInformationAcademiesTrusts.dll"
    ports:
      - "80:8080/tcp"
    env_file:
      - .env
