version: "3.8"
services:
  faker:
    build:
      context: ..
      dockerfile: docker/AcademiesDbFaker.Dockerfile
      args:
        DB_PASSWORD: mySuperStrong_pa55word!!!
    ports:
      - "1433:1433"
    networks:
      - test-ci
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet DfE.FindInformationAcademiesTrusts.dll"
    ports:
      - 80:80/tcp
    networks:
      - test-ci
    environment:
      - ASPNETCORE_ENVIRONMENT=CI
      - ConnectionStrings__AcademiesDb=Server=faker;User Id=sa;Password=mySuperStrong_pa55word!!!;TrustServerCertificate=true;

networks:
  test-ci:
