using DfE.FindInformationAcademiesTrusts.Data;

namespace DfE.FindInformationAcademiesTrusts.Services.School;

public record SchoolInternalContactsServiceModel(Person RegionsGroupLocalAuthorityLead);
