---------------------------------------------------------------------------------------------

-- This script harvests data from the database used by the old cypress tests and transforms it slightly
-- The results are extracted into INSERT statements by a tool (such as Rider Database Tools) and put into HardCodedData.cs

-- This is the data that was originally transformed using this script: 
-- * https://github.com/DFE-Digital/find-information-about-academies-and-trusts/blob/production-2024-08-22.2794/tests/DfE.FindInformationAcademiesTrusts.Data.AcademiesDb.Faker/data/insertScript.sql

-- These are the trusts retrieved:
-- * 'ST MARY''S ACADEMY TRUST' - used by "Testing the search trust functionality" and "Searching for a trust and checking information" old cypress tests
-- * 'ST MARY''S CATHOLIC HIGH SCHOOL ACADEMY TRUST' - used by "Testing the search trust functionality" old cypress test
-- * 'ST MARY''S CATHOLIC PRIMARY SCHOOL' - used by "Testing the search trust functionality" old cypress test
-- * 'PROSPERITY EDUCATION TRUST' - used by "Testing a multi-academy trust" old cypress test

-- These are the transformations applied:
-- * All numeric IDs are prefixed with 99 to prevent clashes with future generated data
--   - Except URN which is prefixed with only one 9 (to prevent int overflow)
-- * The group link table has extra data brought in from the establishments table
---------------------------------------------------------------------------------------------

--Setup variables
DECLARE @TrustNames TABLE
                    (
                        TrustName NVARCHAR(MAX)
                    )
INSERT INTO @TrustNames (TrustName)
VALUES (N'ST MARY''S ACADEMY TRUST'),
       (N'ST MARY''S CATHOLIC HIGH SCHOOL ACADEMY TRUST'),
       (N'ST MARY''S CATHOLIC PRIMARY SCHOOL'),
       (N'PROSPERITY EDUCATION TRUST');

DECLARE @Uids TABLE
              (
                  uid NVARCHAR(MAX)
              )
INSERT INTO @Uids
SELECT [Group UID]
FROM [sip].[gias].[Group]
WHERE [Group Name] IN (SELECT TrustName FROM @TrustNames)

DECLARE @Urns TABLE
              (
                  urn INT
              )
INSERT INTO @Urns
SELECT URN
from gias.GroupLink
WHERE [Group UID] IN (SELECT uid FROM @Uids)
--End setup

--GIAS GROUP
SELECT '99' + [Group UID] AS [Group UID],
       [Group ID],
       [Group Name],
       [Companies House Number],
       [Group Type (code)],
       [Group Type],
       [Closed Date],
       [Group Status (code)],
       [Group Status],
       [Group Contact Street],
       [Group Contact Locality],
       [Group Contact Town],
       [Group Contact Postcode],
       [Head of Group Title],
       [Head of Group First Name],
       [Head of Group Last Name],
       UKPRN,
       [Incorporated on (open date)],
       [Open date]
FROM [gias].[Group]
WHERE [Group UID] IN (SELECT uid FROM @Uids)

--MSTR Trust
SELECT '99' + [Group UID] AS [Group UID], GORregion
FROM mstr.Trust
WHERE [Group UID] IN (SELECT uid FROM @Uids)

--GIAS group link
SELECT '9' + [gl].[URN]        as [URN],
       '99' + [gl].[Group UID] as [Group UID],
       [gl].[Group ID],
       [gl].[Group Name],
       [gl].[Companies House Number],
       [gl].[Group Type (code)],
       [gl].[Group Type],
       [gl].[Closed Date],
       [gl].[Group Status (code)],
       [gl].[Group Status],
       [gl].[Joined date],
       [e].[EstablishmentName],
       [gl].[TypeOfEstablishment (code)],
       [e].[TypeOfEstablishment (name)],
       [gl].[PhaseOfEducation (code)],
       [e].[PhaseOfEducation (name)],
       [e].[LA (code)],
       [e].[LA (name)],
       [gl].[Incorporated on (open date)],
       [gl].[Open date],
       [gl].[URN_GroupUID]
FROM gias.GroupLink gl
         JOIN gias.Establishment e ON gl.URN = e.URN
WHERE [Group UID] IN (SELECT uid FROM @Uids)

--GIAS Establishment
SELECT CAST(CONCAT('9', URN) AS INT) AS URN,
       [LA (code)],
       [LA (name)],
       EstablishmentNumber,
       EstablishmentName,
       [TypeOfEstablishment (code)],
       [TypeOfEstablishment (name)],
       [EstablishmentTypeGroup (code)],
       [EstablishmentTypeGroup (name)],
       [EstablishmentStatus (code)],
       [EstablishmentStatus (name)],
       [ReasonEstablishmentOpened (code)],
       [ReasonEstablishmentOpened (name)],
       OpenDate,
       [ReasonEstablishmentClosed (code)],
       [ReasonEstablishmentClosed (name)],
       CloseDate,
       [PhaseOfEducation (code)],
       [PhaseOfEducation (name)],
       StatutoryLowAge,
       StatutoryHighAge,
       [Boarders (code)],
       [Boarders (name)],
       [NurseryProvision (name)],
       [OfficialSixthForm (code)],
       [OfficialSixthForm (name)],
       [Gender (code)],
       [Gender (name)],
       [ReligiousCharacter (code)],
       [ReligiousCharacter (name)],
       [ReligiousEthos (name)],
       [Diocese (code)],
       [Diocese (name)],
       [AdmissionsPolicy (code)],
       [AdmissionsPolicy (name)],
       SchoolCapacity,
       [SpecialClasses (code)],
       [SpecialClasses (name)],
       CensusDate,
       NumberOfPupils,
       NumberOfBoys,
       NumberOfGirls,
       PercentageFSM,
       [TrustSchoolFlag (code)],
       [TrustSchoolFlag (name)],
       [Trusts (code)],
       [Trusts (name)],
       [SchoolSponsorFlag (name)],
       [SchoolSponsors (name)],
       [FederationFlag (name)],
       [Federations (code)],
       [Federations (name)],
       UKPRN,
       FEHEIdentifier,
       [FurtherEducationType (name)],
       OfstedLastInsp,
       [OfstedSpecialMeasures (code)],
       [OfstedSpecialMeasures (name)],
       LastChangedDate,
       Street,
       Locality,
       Address3,
       Town,
       [County (name)],
       Postcode,
       SchoolWebsite,
       TelephoneNum,
       [HeadTitle (name)],
       HeadFirstName,
       HeadLastName,
       HeadPreferredJobTitle,
       [InspectorateName (name)],
       InspectorateReport,
       DateOfLastInspectionVisit,
       NextInspectionVisit,
       [TeenMoth (name)],
       TeenMothPlaces,
       [CCF (name)],
       [SENPRU (name)],
       [EBD (name)],
       PlacesPRU,
       [FTProv (name)],
       [EdByOther (name)],
       [Section41Approved (name)],
       [SEN1 (name)],
       [SEN2 (name)],
       [SEN3 (name)],
       [SEN4 (name)],
       [SEN5 (name)],
       [SEN6 (name)],
       [SEN7 (name)],
       [SEN8 (name)],
       [SEN9 (name)],
       [SEN10 (name)],
       [SEN11 (name)],
       [SEN12 (name)],
       [SEN13 (name)],
       [TypeOfResourcedProvision (name)],
       ResourcedProvisionOnRoll,
       ResourcedProvisionCapacity,
       SenUnitOnRoll,
       SenUnitCapacity,
       [GOR (code)],
       [GOR (name)],
       [DistrictAdministrative (code)],
       [DistrictAdministrative (name)],
       [AdministrativeWard (code)],
       [AdministrativeWard (name)],
       [ParliamentaryConstituency (code)],
       [ParliamentaryConstituency (name)],
       [UrbanRural (code)],
       [UrbanRural (name)],
       [GSSLACode (name)],
       Easting,
       Northing,
       [MSOA (name)],
       [LSOA (name)],
       SENStat,
       SENNoStat,
       [BoardingEstablishment (name)],
       PropsName,
       [PreviousLA (code)],
       [PreviousLA (name)],
       PreviousEstablishmentNumber,
       [OfstedRating (name)],
       [RSCRegion (name)],
       [Country (name)],
       UPRN,
       SiteName,
       [MSOA (code)],
       [LSOA (code)],
       FSM,
       [BSOInspectorateName (name)],
       CHNumber,
       [EstablishmentAccredited (code)],
       [EstablishmentAccredited (name)],
       [QABName (code)],
       [QABName (name)],
       QABReport,
       AccreditationExpiryDate
FROM gias.Establishment
WHERE [URN] IN (SELECT urn
                from @Urns)

--MIS Establishment
SELECT [Web link],
       CAST(CONCAT('9', URN) AS INT) AS URN,
       LAESTAB,
       [School name],
       [Ofsted phase],
       [Type of education],
       [School open date],
       [Admissions policy],
       [Sixth form],
       [Designated religious character],
       [Religious ethos],
       [Faith grouping],
       [Ofsted region],
       Region,
       [Local authority],
       [Parliamentary constituency],
       Postcode,
       [The income deprivation affecting children index (IDACI) quintile],
       [Total number of pupils],
       [Latest section 8 inspection number since last full inspection],
       [Does the section 8 inspection relate to the URN of the current school?],
       [URN at time of the section 8 inspection],
       [LAESTAB at time of the section 8 inspection],
       [School name at time of the latest section 8 inspection],
       [School type at time of the latest section 8 inspection],
       [Number of section 8 inspections since the last full inspection],
       [Date of latest section 8 inspection],
       [Section 8 inspection publication date],
       [Did the latest section 8 inspection convert to a full inspection?],
       [Section 8 inspection overall outcome],
       [Number of other section 8 inspections since last full inspection],
       [Inspection number of latest full inspection],
       [Inspection type],
       [Inspection type grouping],
       [Event type grouping],
       [Inspection start date],
       [Inspection end date],
       [Publication date],
       [Does the latest full inspection relate to the URN of the current school?],
       [URN at time of latest full inspection],
       [LAESTAB at time of latest full inspection],
       [School name at time of latest full inspection],
       [School type at time of latest full inspection],
       [Overall effectiveness],
       [Category of concern],
       [Quality of education],
       [Behaviour and attitudes],
       [Personal development],
       [Effectiveness of leadership and management],
       [Safeguarding is effective?],
       [Early years provision (where applicable)],
       [Sixth form provision (where applicable)],
       [Previous full inspection number],
       [Previous inspection start date],
       [Previous inspection end date],
       [Previous publication date],
       [Does the previous full inspection relate to the URN of the current school?],
       [URN at time of previous full inspection],
       [LAESTAB at time of previous full inspection],
       [School name at time of previous full inspection],
       [School type at time of previous full inspection],
       [Previous full inspection overall effectiveness],
       [Previous category of concern],
       [Previous quality of education],
       [Previous behaviour and attitudes],
       [Previous personal development],
       [Previous effectiveness of leadership and management],
       [Previous safeguarding is effective?],
       [Previous early years provision (where applicable)],
       [Previous sixth form provision (where applicable)]
FROM mis.Establishments
WHERE [URN] IN (SELECT urn
                from @Urns)

--GIAS Governance
SELECT '99' + GID AS GID,
       URN,
       '99' + UID AS UID,
       [Companies House Number],
       Role,
       Title,
       [Forename 1],
       [Forename 2],
       Surname,
       [Date of appointment],
       [Date term of office ends/ended],
       [Appointing body]
FROM gias.Governance
WHERE [UID] IN (SELECT uid FROM @Uids)

--Mstr Governance
SELECT CAST(CONCAT('99', SK) AS INT) AS SK,
       FK_Trust,
       FK_GovernanceRoleType,
       '99' + GID                    AS GID,
       Title,
       Forename1,
       Forename2,
       Surname,
       Email,
       [Date of appointment],
       [Date term of office ends/ended],
       [Appointing body],
       Modified,
       [Modified By]
FROM mstr.TrustGovernance
WHERE [GID] IN (SELECT GID
                FROM gias.Governance
                WHERE [UID] IN (SELECT uid FROM @Uids))

-- cdm account
SELECT Id,
       accountcategorycode,
       accountclassificationcode,
       accountid,
       accountnumber,
       accountratingcode,
       address1_addressid,
       address1_addresstypecode,
       address1_city,
       address1_composite,
       address1_country,
       address1_county,
       address1_fax,
       address1_freighttermscode,
       address1_latitude,
       address1_line1,
       address1_line2,
       address1_line3,
       address1_longitude,
       address1_name,
       address1_postalcode,
       address1_postofficebox,
       address1_primarycontactname,
       address1_shippingmethodcode,
       address1_stateorprovince,
       address1_telephone1,
       address1_telephone2,
       address1_telephone3,
       address1_upszone,
       address1_utcoffset,
       address2_addressid,
       address2_addresstypecode,
       address2_city,
       address2_composite,
       address2_country,
       address2_county,
       address2_fax,
       address2_freighttermscode,
       address2_latitude,
       address2_line1,
       address2_line2,
       address2_line3,
       address2_longitude,
       address2_name,
       address2_postalcode,
       address2_postofficebox,
       address2_primarycontactname,
       address2_shippingmethodcode,
       address2_stateorprovince,
       address2_telephone1,
       address2_telephone2,
       address2_telephone3,
       address2_upszone,
       address2_utcoffset,
       adx_createdbyipaddress,
       adx_createdbyusername,
       adx_modifiedbyipaddress,
       adx_modifiedbyusername,
       aging30,
       aging30_base,
       aging60,
       aging60_base,
       aging90,
       aging90_base,
       businesstypecode,
       createdby,
       createdbyexternalparty,
       createdbyexternalpartyname,
       createdbyexternalpartyyominame,
       createdbyname,
       createdbyyominame,
       createdon,
       createdonbehalfby,
       createdonbehalfbyname,
       createdonbehalfbyyominame,
       creditlimit,
       creditlimit_base,
       creditonhold,
       customersizecode,
       customertypecode,
       defaultpricelevelid,
       defaultpricelevelidname,
       description,
       donotbulkemail,
       donotbulkpostalmail,
       donotemail,
       donotfax,
       donotphone,
       donotpostalmail,
       donotsendmm,
       emailaddress1,
       emailaddress2,
       emailaddress3,
       entityimage_timestamp,
       entityimage_url,
       entityimageid,
       exchangerate,
       fax,
       followemail,
       ftpsiteurl,
       importsequencenumber,
       industrycode,
       isprivate,
       lastonholdtime,
       lastusedincampaign,
       marketcap,
       marketcap_base,
       marketingonly,
       masteraccountidname,
       masteraccountidyominame,
       masterid,
       merged,
       modifiedby,
       modifiedbyexternalparty,
       modifiedbyexternalpartyname,
       modifiedbyexternalpartyyominame,
       modifiedbyname,
       modifiedbyyominame,
       modifiedon,
       modifiedonbehalfby,
       modifiedonbehalfbyname,
       modifiedonbehalfbyyominame,
       msa_managingpartnerid,
       msa_managingpartneridname,
       msa_managingpartneridyominame,
       msdyn_accountkpiid,
       msdyn_accountkpiidname,
       msdyn_gdproptout,
       msdyn_salesaccelerationinsightid,
       msdyn_salesaccelerationinsightidname,
       msdyn_segmentid,
       msdyn_segmentidname,
       msft_datastate,
       name,
       numberofemployees,
       onholdtime,
       opendeals,
       opendeals_date,
       opendeals_state,
       openrevenue,
       openrevenue_base,
       openrevenue_date,
       openrevenue_state,
       originatingleadid,
       originatingleadidname,
       originatingleadidyominame,
       overriddencreatedon,
       ownerid,
       owneridname,
       owneridtype,
       owneridyominame,
       ownershipcode,
       owningbusinessunit,
       owningbusinessunitname,
       owningteam,
       owninguser,
       parentaccountid,
       parentaccountidname,
       parentaccountidyominame,
       participatesinworkflow,
       paymenttermscode,
       preferredappointmentdaycode,
       preferredappointmenttimecode,
       preferredcontactmethodcode,
       preferredequipmentid,
       preferredequipmentidname,
       preferredserviceid,
       preferredserviceidname,
       preferredsystemuserid,
       preferredsystemuseridname,
       preferredsystemuseridyominame,
       primarycontactid,
       primarycontactidname,
       primarycontactidyominame,
       primarysatoriid,
       primarytwitterid,
       processid,
       revenue,
       revenue_base,
       sharesoutstanding,
       shippingmethodcode,
       sic,
       sip_9gridboxbanding,
       sip_academyprojectlead,
       sip_academyriskgrade,
       sip_academywheretrustsat,
       sip_academywheretrustsatname,
       sip_academywheretrustsatyominame,
       sip_administrativedistrict,
       sip_agerange,
       sip_amsdlead,
       sip_amsdleadname,
       sip_amsdleadyominame,
       sip_amsdterritoryid,
       sip_amsdterritoryidname,
       sip_behaviourandattitudes,
       sip_capacitybeyondopenandpipeline,
       sip_closurereasons,
       sip_compaddress,
       sip_companieshousefilinghistory,
       sip_companieshousenumber,
       sip_companieshouseofficersurl,
       sip_compositeaddress,
       sip_concerntotaldart,
       sip_concerntotalkim,
       sip_constituencyid,
       sip_constituencyidname,
       sip_countofprimaryphase,
       sip_currentsinglelistgrouping,
       sip_dateactionplannedfor,
       sip_dateclosed,
       sip_dateenteredontosinglelist,
       sip_dateofestablishment,
       sip_dateofgroupingdecision,
       sip_dateofjoiningtrust,
       sip_dateoflasttrustreview,
       sip_dateoflatestsection8inspection,
       sip_dateoftrustreviewmeeting,
       sip_dfenumber,
       sip_diocesanmat,
       sip_diocesanmatpercentagego,
       sip_dioceseid,
       sip_dioceseidname,
       sip_displayepprimarysections,
       sip_displayepsecondarysections,
       sip_displayeptrustprimary,
       sip_displayeptrustsecondary,
       sip_dtrtoollink,
       sip_earlyyearsprovisionwhereapplicable,
       sip_effectivenessofleadershipandmanagement,
       sip_efficiencyicfpreviewcompleted,
       sip_efficiencyicfpreviewother,
       sip_establishmentlinktype,
       sip_establishmentnumber,
       sip_establishmenttypeid,
       sip_establishmenttypeidname,
       sip_establismenttypegroupid,
       sip_establismenttypegroupidname,
       sip_expectedopeningdate,
       sip_externalgovernancereviewdate,
       sip_financeriskgroup,
       sip_financeriskgroupmajorrisks,
       sip_financeriskgroupriskscore,
       sip_financeriskgrouptotalrisks,
       sip_fntistatus,
       sip_followuplettersent,
       sip_formswitcher,
       sip_freeschoolmeals,
       sip_fundingagreementpageurl,
       sip_futureplans,
       sip_gorregion,
       sip_governanceandtrustboard,
       sip_governanceriskgroup,
       sip_governanceriskgroupmajorrisks,
       sip_governanceriskgroupriskscore,
       sip_governanceriskgrouptotalrisks,
       sip_hasthematsponsorreceivedragfmdifotherfund,
       sip_howmuchandwhatitwasfor,
       sip_inadequaterequiresimprovementschoolscalc,
       sip_inadequaterequiresimprovementschoolscalc_date,
       sip_inadequaterequiresimprovementschoolscalc_state,
       sip_incorporateddate,
       sip_inspectionforcurrenturn,
       sip_integratedcurriculumfinancialplanningicfp,
       sip_ipamaps,
       sip_irregularityriskgroup,
       sip_irregularityriskgroupmajorrisks,
       sip_irregularityriskgroupriskscore,
       sip_irregularityriskgrouptotalrisks,
       sip_keypeoplebios,
       sip_knowledgearticlefinanceglossary,
       sip_knowledgearticlefinanceglossaryname,
       sip_laestabnumber,
       sip_laestabtext,
       sip_latestmatbandingsource,
       sip_latestmatreviewscore,
       sip_latitude,
       sip_lbawarelandnotregistered,
       sip_lbawarelandnotregisteredexplained,
       sip_lbcurrentbuildinglandowner,
       sip_leadamsdterritoryid,
       sip_leadamsdterritoryidname,
       sip_leadrscareaid,
       sip_leadrscareaidname,
       sip_linktoofstedpage,
       sip_linktoworkplaceforefficiencyicfpreview,
       sip_localauthorityareaid,
       sip_localauthorityareaidname,
       sip_localauthoritynumber,
       sip_longitude,
       sip_maincontactsemail,
       sip_maincontactsphone,
       sip_mainreasonforintervention,
       sip_maintrustcontactid,
       sip_maintrustcontactidname,
       sip_managementletterinternalaudit,
       sip_mathsscore,
       sip_mathsscorecategory,
       sip_nationalsponsoroversight,
       sip_newtrustdate,
       sip_newurn,
       sip_noeducationperformacedatamessage,
       sip_noeducationperformancedatatrustmessage,
       sip_noofphaseallthrough,
       sip_noofphaseallthrough_date,
       sip_noofphaseallthrough_state,
       sip_noofprimaryphase,
       sip_noofprimaryphase_date,
       sip_noofprimaryphase_state,
       sip_noofsecondaryphase,
       sip_noofsecondaryphase_date,
       sip_noofsecondaryphase_state,
       sip_numberacademiesintrust,
       sip_numberofacademiescalculated,
       sip_numberofacademiescalculated_date,
       sip_numberofacademiescalculated_state,
       sip_numberofacademiesintrust,
       sip_numberofactivedartconcerns,
       sip_numberofactivedartconcerns_date,
       sip_numberofactivedartconcerns_state,
       sip_numberofactivekimconcerns,
       sip_numberofactivekimconcerns_date,
       sip_numberofactivekimconcerns_state,
       sip_numberofdartconcernsacademy,
       sip_numberofdartconcernsacademy_date,
       sip_numberofdartconcernsacademy_state,
       sip_numberofkimconcernsacademy,
       sip_numberofkimconcernsacademy_date,
       sip_numberofkimconcernsacademy_state,
       sip_numberofoutstandingschoolscalculated,
       sip_numberofoutstandingschoolscalculated_date,
       sip_numberofoutstandingschoolscalculated_state,
       sip_numberofpupils,
       sip_numberofrequiresimprovementinadequateacad,
       sip_ofstedgoodschoolsupdateddate,
       sip_ofstedinspectiondate,
       sip_ofstedinspectionrating,
       sip_ofstedrating,
       sip_ofstedratingupdated,
       sip_ofstedtotalgood,
       sip_ofstedtotalinadequat,
       sip_ofstedtotalinadequate,
       sip_ofstedtotaloutstanding,
       sip_ofstedtotalrequiresimprovement,
       sip_organisationtype,
       sip_originatingapplicationid,
       sip_originatingapplicationidname,
       sip_originatingapplyingschoolid,
       sip_originatingapplyingschoolidname,
       sip_overallriskgroup,
       sip_overallriskgroupmajorrisks,
       sip_overallriskgroupriskscore,
       sip_overallriskgrouptotalrisks,
       sip_overviewoffinancialstatusofthetrust,
       sip_parentcompanyreference,
       sip_percentageoffreeschoolmeals,
       sip_performanceguid,
       sip_personaldevelopment,
       sip_phase,
       sip_pipelineacademy,
       sip_pipelinefreeschool,
       sip_predecessorestablishment,
       sip_predecessorestablishmentname,
       sip_predecessorestablishmentyominame,
       sip_predecessorurn,
       sip_predictedchanceofchangeoccuring,
       sip_predictedchangeinprogress8score,
       sip_previousinspectionfor,
       sip_previousofstedinspectiondate,
       sip_previousofstedinspectionrating,
       sip_previousofstedrating,
       sip_previoustrust,
       sip_previoustrustname,
       sip_previoustrustyominame,
       sip_prioritisedforareview,
       sip_probabilityofdeclining,
       sip_probabilityofimproving,
       sip_probabilityofstayingthesame,
       sip_projectleadforpipelineacademy,
       sip_projectroute,
       sip_proposedmemberoftrustid,
       sip_proposedmemberoftrustidname,
       sip_proposedmemberoftrustidyominame,
       sip_pupilpremiumstrategy,
       sip_qualityofeducation,
       sip_ratgradedescription,
       sip_readingscore,
       sip_readingscorecategory,
       sip_relationshipmanagerid,
       sip_relationshipmanageridname,
       sip_relationshipmanageridyominame,
       sip_religiouscharacterid,
       sip_religiouscharacteridname,
       sip_religiousethosid,
       sip_religiousethosidname,
       sip_riskratingnum,
       sip_risksissues,
       sip_routeofproject,
       sip_rschtbtrustapprovaldate,
       sip_satlaestabnumber,
       sip_satpredecessorurn,
       sip_saturn,
       sip_schoolcapacity,
       sip_schoolfinancialbenchmarklink,
       sip_schoolimprovementstrategy,
       sip_scpnassumptions,
       sip_scpnprojectedpupilonrollyear1,
       sip_scpnprojectedpupilonrollyear2,
       sip_scpnprojectedpupilonrollyear3,
       sip_section8inspectionfor,
       sip_section8inspectionoveralloutcome,
       sip_sfsoterritories,
       sip_sharepointfinancialglossary,
       sip_sharepointsdocs,
       sip_shortofstedinspcountsinceofstedinspdate,
       sip_shortofstedinspectiondate,
       sip_sixthformprovisionwhereapplicable,
       sip_sk,
       sip_sponsorapprovaldate,
       sip_sponsorcoordinator,
       sip_sponsorname,
       sip_sponsoroverview,
       sip_sponsorreferencenumber,
       sip_sponsorrestrictions,
       sip_sponsorstatus,
       sip_statutoryhighage,
       sip_statutorylowage,
       sip_stubtrust,
       sip_topsliceorchargingpolicy,
       sip_totalnumberofrisks,
       sip_totalriskscore,
       sip_transfer,
       sip_transfername,
       sip_transferstatus,
       sip_transferstatusname,
       sip_transfertype,
       sip_transfertypename,
       sip_triggerflow,
       sip_trustconcernasnumber,
       sip_trusthighestconcernlevel,
       sip_trustperformanceandriskdateofmeeting,
       sip_trustreferencenumber,
       sip_trustrelationshipmanager,
       sip_trustrelationshipmanagername,
       sip_trustrelationshipmanageryominame,
       sip_trustreviewwriteup,
       sip_trustriskgrade,
       '99' + [sip_uid] AS [sip_uid],
       sip_ukprn,
       sip_upin,
       sip_urn,
       sip_urnatcurrentofstedinspection,
       sip_urnatpreviousofstedinspection,
       sip_urnsection8ofstedinspection,
       sip_urnwholenumber,
       sip_wipsummarygoestominister,
       sip_writingscore,
       sip_writingscorecategory,
       slaid,
       slainvokedid,
       slainvokedidname,
       slaname,
       stageid,
       statecode,
       statuscode,
       stockexchange,
       teamsfollowed,
       telephone1,
       telephone2,
       telephone3,
       territorycode,
       territoryid,
       territoryidname,
       tickersymbol,
       timespentbymeonemailandmeetings,
       timezoneruleversionnumber,
       transactioncurrencyid,
       transactioncurrencyidname,
       traversedpath,
       utcconversiontimezonecode,
       versionnumber,
       websiteurl,
       yominame
FROM cdm.account
WHERE sip_uid IN (SELECT uid FROM @Uids)

-- cdm systemuser
SELECT *
FROM [cdm].[systemuser]
WHERE [systemuserid] IN (SELECT [sip_trustrelationshipmanager]
                         FROM cdm.account
                         WHERE sip_uid IN (SELECT uid FROM @Uids))
   OR [systemuserid] IN (SELECT [sip_amsdlead]
                         FROM cdm.account
                         WHERE sip_uid IN (SELECT uid FROM @Uids))
    