using System.Diagnostics.CodeAnalysis;

namespace DfE.FindInformationAcademiesTrusts.AcademiesApiResponseModels;

[ExcludeFromCodeCoverage] // API response model POCO
public class EstablishmentResponse
{
    public string? Urn { get; set; }
    public string? LocalAuthorityCode { get; set; }
    public string? LocalAuthorityName { get; set; }
    public string? EstablishmentNumber { get; set; }
    public string? EstablishmentName { get; set; }
    public NameAndCodeResponse? EstablishmentType { get; set; }
    public NameAndCodeResponse? EstablishmentTypeGroup { get; set; }
    public NameAndCodeResponse? EstablishmentStatus { get; set; }
    public NameAndCodeResponse? ReasonEstablishmentOpened { get; set; }
    public string? OpenDate { get; set; }
    public NameAndCodeResponse? ReasonEstablishmentClosed { get; set; }
    public string? CloseDate { get; set; }
    public NameAndCodeResponse? PhaseOfEducation { get; set; }
    public string? StatutoryLowAge { get; set; }
    public string? StatutoryHighAge { get; set; }
    public NameAndCodeResponse? Boarders { get; set; }
    public string? NurseryProvision { get; set; }
    public NameAndCodeResponse? OfficialSixthForm { get; set; }
    public NameAndCodeResponse? Gender { get; set; }
    public NameAndCodeResponse? ReligiousCharacter { get; set; }
    public string? ReligiousEthos { get; set; }
    public NameAndCodeResponse? Diocese { get; set; }
    public NameAndCodeResponse? AdmissionsPolicy { get; set; }
    public string? SchoolCapacity { get; set; }
    public NameAndCodeResponse? SpecialClasses { get; set; }
    public CensusResponse? Census { get; set; }
    public NameAndCodeResponse? TrustSchoolFlag { get; set; }
    public NameAndCodeResponse? Trusts { get; set; }
    public string? SchoolSponsorFlag { get; set; }
    public string? SchoolSponsors { get; set; }
    public string? FederationFlag { get; set; }
    public NameAndCodeResponse? Federations { get; set; }
    public string? Ukprn { get; set; }
    public string? FeheiIdentifier { get; set; }
    public string? FurtherEducationType { get; set; }
    public string? OfstedLastInspection { get; set; }
    public NameAndCodeResponse? OfstedSpecialMeasures { get; set; }
    public string? LastChangedDate { get; set; }
    public AddressResponse? Address { get; set; }
    public string? SchoolWebsite { get; set; }
    public string? TelephoneNumber { get; set; }
    public string? HeadteacherTitle { get; set; }
    public string? HeadteacherFirstName { get; set; }
    public string? HeadteacherLastName { get; set; }
    public string? HeadteacherPreferredJobTitle { get; set; }
    public string? InspectorateName { get; set; }
    public string? InspectorateReport { get; set; }
    public string? DateOfLastInspectionVisit { get; set; }
    public string? DateOfNextInspectionVisit { get; set; }
    public string? TeenMoth { get; set; }
    public string? TeenMothPlaces { get; set; }
    public string? Ccf { get; set; }
    public string? Senpru { get; set; }
    public string? Ebd { get; set; }
    public string? PlacesPru { get; set; }
    public string? FtProv { get; set; }
    public string? EdByOther { get; set; }
    public string? Section14Approved { get; set; }
    public string? Sen1 { get; set; }
    public string? Sen2 { get; set; }
    public string? Sen3 { get; set; }
    public string? Sen4 { get; set; }
    public string? Sen5 { get; set; }
    public string? Sen6 { get; set; }
    public string? Sen7 { get; set; }
    public string? Sen8 { get; set; }
    public string? Sen9 { get; set; }
    public string? Sen10 { get; set; }
    public string? Sen11 { get; set; }
    public string? Sen12 { get; set; }
    public string? Sen13 { get; set; }
    public string? TypeOfResourcedProvision { get; set; }
    public string? ResourcedProvisionOnRoll { get; set; }
    public string? ResourcedProvisionOnCapacity { get; set; }
    public string? SenUnitOnRoll { get; set; }
    public string? SenUnitCapacity { get; set; }
    public NameAndCodeResponse? Gor { get; set; }
    public NameAndCodeResponse? DistrictAdministrative { get; set; }
    public NameAndCodeResponse? AdministractiveWard { get; set; }
    public NameAndCodeResponse? ParliamentaryConstituency { get; set; }
    public NameAndCodeResponse? UrbanRural { get; set; }
    public string? GsslaCode { get; set; }
    public string? Easting { get; set; }
    public string? Northing { get; set; }
    public string? CensusAreaStatisticWard { get; set; }
    public NameAndCodeResponse? Msoa { get; set; }
    public NameAndCodeResponse? Lsoa { get; set; }
    public string? SenStat { get; set; }
    public string? SenNoStat { get; set; }
    public string? BoardingEstablishment { get; set; }
    public string? PropsName { get; set; }
    public NameAndCodeResponse? PreviousLocalAuthority { get; set; }
    public string? PreviousEstablishmentNumber { get; set; }
    public string? OfstedRating { get; set; }
    public string? RscRegion { get; set; }
    public string? Country { get; set; }
    public string? Uprn { get; set; }
    public MisEstablishmentResponse? MisEstablishment { get; set; }
    public MisfeaResponse? MisFurtherEducationEstablishment { get; set; }

    public ViewAcademyConversionResponse? ViewAcademyConversion { get; set; }
    public SmartDataResponse? SmartData { get; set; }
    public PlaceholderResponse? Financial { get; set; }
    public PlaceholderResponse? Concerns { get; set; }
}
