name: Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**.tf'
  pull_request:
    paths:
      - 'terraform/**.tf'

jobs:
  terraform-validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check for terraform version mismatch
        run: |
          DOTFILE_VERSION=$(cat terraform/.terraform-version)
          TERRAFORM_IMAGE_REFERENCES=$(grep "uses: docker://hashicorp/terraform" .github/workflows/continuous-integration-terraform.yml | grep -v TERRAFORM_IMAGE_REFERENCES | wc -l | tr -d ' ')
          if [ "$(grep "docker://hashicorp/terraform:${DOTFILE_VERSION}" .github/workflows/continuous-integration-terraform.yml | wc -l | tr -d ' ')" != "$TERRAFORM_IMAGE_REFERENCES" ]
          then
            echo -e "\033[1;31mError: terraform version in .terraform-version file does not match docker://hashicorp/terraform versions in .github/workflows/continuous-integration-terraform.yml"
            exit 1
          fi

      - name: Validate Terraform docs
        uses: terraform-docs/gh-actions@aeae0038ed47a547e0c0fca5c059d3335f48fb25 # v1.3.0
        with:
          working-dir: terraform
          config-file: .terraform-docs.yml
          output-file: README.md
          output-method: inject
          fail-on-diff: true

      - name: Remove azure backend
        run: rm ./terraform/backend.tf

      - name: Run a Terraform init
        uses: docker://hashicorp/terraform:1.10.5@sha256:679ac5e095bf550bc726742cd12efa6050f0913080df479fdabfeb202953af28
        with:
          entrypoint: terraform
          args: -chdir=terraform init

      - name: Run a Terraform validate
        uses: docker://hashicorp/terraform:1.10.5@sha256:679ac5e095bf550bc726742cd12efa6050f0913080df479fdabfeb202953af28
        with:
          entrypoint: terraform
          args: -chdir=terraform validate

      - name: Run a Terraform format check
        uses: docker://hashicorp/terraform:1.10.5@sha256:679ac5e095bf550bc726742cd12efa6050f0913080df479fdabfeb202953af28
        with:
          entrypoint: terraform
          args: -chdir=terraform fmt -check=true -diff=true

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4
        with:
          tflint_version: v0.44.1

      - name: Run TFLint
        working-directory: terraform
        run: tflint -f compact

      - name: Run TFSec
        uses: aquasecurity/tfsec-pr-commenter-action@7a44c5dcde5dfab737363e391800629e27b6376b # v1.3.1
        with:
          github_token: ${{ github.token }}
