name: Lint project
on:
  pull_request:
    branches: [ main, '**-feature' ]
    types: [ opened, synchronize, reopened]

env:
  NODE_VERSION: 18.13.0
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
    - uses: actions/checkout@v4
      name: Check out repository

    - uses: actions/setup-node@v4
      name: Set up Node.js
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
        cache-dependency-path: |
          DfE.FindInformationAcademiesTrusts/package-lock.json
          tests/DFE.FindInformationAcademiesTrusts.CypressTests/package-lock.json

    - name: Install dependencies
      run: |
        (cd DfE.FindInformationAcademiesTrusts && npm ci)
        (cd tests/DFE.FindInformationAcademiesTrusts.CypressTests && npm ci)

    - name: Analyse front end assets
      run: |
        cd DfE.FindInformationAcademiesTrusts && npm run lint

    - name: Analyse playwright tests
      run: |
        cd tests/\DFE.FindInformationAcademiesTrusts.CypressTests && npm run lint
