name: Deployment smoke tests
run-name: Deployment smoke tests for '${{ github.event.deployment.environment }}' - `${{github.event.workflow_run.head_branch}}`

concurrency:
  group: ${{ github.workflow }}-${{ github.event.deployment.environment }}-${{ github.event.workflow_run.status == 'completed' && github.event.workflow.name == 'Deploy to environment' && github.event.deployment_status.state == 'success' }}
  cancel-in-progress: true

on:
  deployment_status:

jobs:
  playwright:
    name: Deployment smoke tests
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.status == 'completed' && github.event.workflow.name == 'Deploy to environment' && github.event.deployment_status.state == 'success'}}
    environment: ${{ github.event.deployment.environment }}
    defaults:
      run:
        working-directory: tests/playwright
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chrome

      - name: Run Playwright deployment tests
        env:
          CI: true
          PLAYWRIGHT_BASEURL: ${{ secrets.BASE_URL }}
        run: npx playwright test --project=deployment-tests

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 7
