name: Run Docker build

on:
  pull_request:
    paths:
      - docker/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [
          "final",
          "initcontainer"
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          file: './docker/Dockerfile'
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha
          target: ${{ matrix.stage }}
          push: false
