name: Scan Docker image

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [
          "final",
          "initcontainer"
        ]
    outputs:
      image: ${{ steps.build.outputs.imageid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        id: build
        with:
          file: './docker/Dockerfile'
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          load: true
          cache-from: type=gha
          cache-to: type=gha
          target: ${{ matrix.stage }}
          push: false

      - name: Export docker image as tar
        run: docker save -o ${{ matrix.stage }}-${{ github.ref_name }}.tar ${{ steps.build.outputs.imageid }}

      - name: Scan Docker image for CVEs
        uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # 0.31.0
        with:
          input: ${{ matrix.stage }}-${{ github.ref_name }}.tar
          format: 'sarif'
          output: 'trivy-results.sarif'
          limit-severities-for-sarif: true
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
