name: Run Docker build

on:
  pull_request:
    paths:
      - docker/Dockerfile
      - docker/FakeDataGenerator.Dockerfile
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [
          "Dockerfile",
          "FakeDataGenerator.Dockerfile"
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          file: './docker/${{ matrix.image }}'
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha
          push: false
