name: Integration tests
run-name: Integration tests for '${{ inputs.environment }}' - `${{ inputs.branch-name }}`

on:
  workflow_call:
    inputs: 
      environment: 
        required: true
        type: string
      branch-name: 
        required: true
        type: string

jobs:
  playwright:
    name: Integration tests
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: tests/playwright
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }} # does this need to be passed down?

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chrome

      - name: Run Playwright deployment tests
        env:
          PLAYWRIGHT_BASEURL: ${{ secrets.BASE_URL }} # does this need to be passed down?
        run: npx playwright test --project=deployment-tests

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 7
