name: Run mock tests

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened]
  push:
    branches: [ main ]

jobs:
  playwright:
    name: Mock UI tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tests/playwright
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start services
        working-directory: ./docker
        run: docker compose -f docker-compose.ci.yml up -d

      - name: Run Playwright tests
        env:
          CI: true
          PLAYWRIGHT_BASEURL: "http://localhost"
          WIREMOCK_BASEURL: "http://localhost:8080"
        run: npx playwright test ui-tests/* accessibility-tests/*

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 7

      - name: Stop services
        if: always()
        working-directory: ./docker
        run: docker compose -f docker-compose.ci.yml stop
