name: Playwright tests
run-name: Playwright tests for '${{ github.event.deployment.environment }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.deployment.environment }}

on:
  deployment_status:

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  playwright:
    name: Playwright tests
    runs-on: ubuntu-22.04
    if: ${{ github.event.deployment_status.state }} == 'success' && ${{ github.event.deployment_status.environment }} == 'Deploy to environment'
    environment: ${{ github.event.deployment.environment }}
    defaults:
      run:
        working-directory: tests/playwright
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          CI: true
          PLAYWRIGHT_BASEURL: ${{ secrets.BASE_URL }}
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 7
