name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.gitignore'
      - '!**.DotSettings'
      - '!**.md'
      - '!.github/**'
      - '!terraform/**'
  pull_request:
    branches: [ main, '**-feature' ]
    types: [ opened, synchronize, reopened]
    paths:
      - '**'
      - '!.gitignore'
      - '!**.DotSettings'
      - '!**.md'
      - '!.github/**'
      - '!terraform/**'

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install other dotnet tools (including stryker, code coverage and entity framework cli)
      run: dotnet tool restore

    - name: Build solution
      run: |
        dotnet restore DfE.FindInformationAcademiesTrusts
        dotnet build DfE.FindInformationAcademiesTrusts -c Release

    - name: Run mutation tests
      run: dotnet stryker

    - name: Ensure there are no pending migrations
      run: dotnet ef migrations has-pending-model-changes --context FiatDbContext --project DfE.FindInformationAcademiesTrusts.Data.FiatDb --startup-project DfE.FindInformationAcademiesTrusts
