name: Run security scanner tests

on:
  workflow_run:
    workflows: ["Deploy to environment"]
    types:
      - completed

jobs:
  run-tests-with-zap:
    name: Run Playwright tests with OWASP ZAP
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with scanner
        env:
          HTTP_PROXY: http://zap:8080
          NO_PROXY: ".google-analytics.com,.googletagmanager.com,.microsoftonline.com,.gvt1.com"
          PLAYWRIGHT_BASEURL: ${{ secrets.PLAYWRIGHT_BASEURL }}
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
        run: |
          docker-compose -f tests/playwright/docker-compose.yml up --exit-code-from playwright

      - name: Get git sha
        if: '!cancelled()'
        run: |
          CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
          echo "checked_out_sha=${CHECKED_OUT_SHA}" >> $GITHUB_ENV

      - name: Azure login with SPN
        if: '!cancelled()'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OWASP_AZ_CREDENTIALS }}

      - name: Push report to blob storage
        if: '!cancelled()'
        uses: azure/CLI@v1
        id: azure
        with:
          azcliversion: 2.49.0
          inlineScript: |
            az storage blob upload \
              --container-name ${{ secrets.OWASP_STORAGE_CONTAINER_NAME }} \
              --account-name ${{ secrets.OWASP_STORAGE_ACCOUNT_NAME }} \
              --file "tests/playwright/zap-reports/ZAP-Report.html" \
              --name "Dfe.FindInformationAcademiesTrusts/${{ env.checked_out_sha }}/ZAP-Report.html" \
              --auth-mode login \
              --overwrite
