name: Run security scanner tests

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Deploy to environment"]
  #   types:
  #     - completed

env:
  ZAP_ADDRESS: localhost
  ZAP_PORT: 9876
  ZAP_API_KEY: 5c93eec3-b5c0-4252-9061-017ebff89450

jobs:
  run-tests-with-zap:
    name: Run Playwright tests with OWASP ZAP
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/playwright
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create directory on runner
        run: |
          mkdir -m 666 ${{ github.workspace }}/zapoutput

      - name: Start ZAP container
        env:
          ZAP_PORT: 9876
        run: docker run --name zap_container --rm -d -v ${{ github.workspace }}/zapoutput:/zap/wrk:rw -u zap -p ${{ env.ZAP_PORT }}:${{ env.ZAP_PORT }} -i owasp/zap2docker-stable zap.sh -daemon -port ${{ env.ZAP_PORT }} -host 0.0.0.0 -config api.key=${{ env.ZAP_API_KEY }} -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config network.localServers.mainProxy.alpn.enabled=false -config network.localServers.mainProxy.address=0.0.0.0

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chrome

      - name: Run Playwright tests
        env:
          CI: true
          PLAYWRIGHT_BASEURL: ${{ secrets.BASE_URL }}
          HTTP_PROXY: "http://${{ env.ZAP_ADDRESS }}:${{ env.ZAP_PORT }}"
          NO_PROXY: ".gvt1.com"
          ZAP: true
          ZAP_API_KEY: ${{ env.ZAP_API_KEY }}
          ZAP_ADDRESS: ${{ env.ZAP_ADDRESS }}
          ZAP_PORT: ${{ env.ZAP_PORT }}
        run: npx playwright test --project=zap-tests

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 7

      - name: Get git sha
        if: '!cancelled()'
        run: |
          CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
          echo "checked_out_sha=${CHECKED_OUT_SHA}" >> $GITHUB_ENV

      - name: Azure login with SPN
        if: '!cancelled()'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OWASP_AZ_CREDENTIALS }}

      - name: Push report to blob storage
        if: '!cancelled()'
        uses: azure/CLI@v1
        id: azure
        with:
          azcliversion: 2.49.0
          inlineScript: |
            az storage blob upload \
              --container-name ${{ secrets.OWASP_STORAGE_CONTAINER_NAME }} \
              --account-name ${{ secrets.OWASP_STORAGE_ACCOUNT_NAME }} \
              --file "${{ github.workspace }}/zapoutput/ZAP-Report.html" \
              --name "Dfe.FindInformationAcademiesTrusts/${{ env.checked_out_sha }}/ZAP-Report.html" \
              --auth-mode login \
              --overwrite
      
      - name: Stop ZAP container
        if: always()
        run: docker stop zap_container
