name: Run smoke deployment tests
run-name: Deployment tests for '${{ inputs.environment }}' - `${{ inputs.branch-name }}`

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch-name:
        required: true
        type: string
env:
  NODE_VERSION: 18.13.0
  PLAYWRIGHT_VERSION: default
  LAST_COMMIT_SHA: default

jobs:
  playwright:
    name: Smoke deployment tests
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: tests/playwright
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set SHA environment variable
        run: |
          echo "LAST_COMMIT_SHA=${GITHUB_SHA:(-7)}" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        name: Set up Node.js
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: |
            DfE.FindInformationAcademiesTrusts/package-lock.json
            tests/playwright/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Pin Playwright cache key
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION="$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")"
          PIN_VERSION=${PLAYWRIGHT_VERSION}-`date +%Y-%m-%d`
          echo "PLAYWRIGHT_VERSION=$PIN_VERSION" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright deployment tests
        env:
          PLAYWRIGHT_BASEURL: ${{ secrets.BASE_URL }}
          AUTH_BYPASS_SECRET: ${{ secrets.TEST_OVERRIDE_PLAYWRIGHT_TEST_SECRET}}
        run: npm run test:deployment

      - name: Prepare report for upload
        run: |
          zip -qq -r ${{ inputs.environment }}-${{ env.LAST_COMMIT_SHA }}.zip ./playwright-report/

      - name: Azure login with SPN
        if: '!cancelled()'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CI_REPORTS_AZ_CREDENTIALS }}

      - name: Push report to blob storage
        if: '!cancelled()'
        uses: azure/CLI@v1
        id: azure
        with:
          azcliversion: 2.53.0
          inlineScript: |
            GIT_REF=${{ github.base_ref }}
            GIT_BRANCH=${GIT_REF//\//-}
            az storage blob upload \
              --container-name ${{ secrets.CI_REPORTS_STORAGE_CONTAINER_NAME }} \
              --account-name ${{ secrets.CI_REPORTS_STORAGE_ACCOUNT_NAME }} \
              --file "./tests/playwright/${{ inputs.environment }}-${{ env.LAST_COMMIT_SHA }}.zip" \
              --name "Dfe.FindInformationAcademiesTrusts/$GIT_BRANCH/test-deployment-${{ env.LAST_COMMIT_SHA }}.zip" \
              --auth-mode login \
              --overwrite
