name: Run automated UI and accessibility tests
run-name: UI tests for '${{ inputs.environment }}' - `${{ inputs.branch-name }}`

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch-name:
        required: true
        type: string
    secrets:
      BASE_URL:
        required: true
      TEST_OVERRIDE_CYPRESS_TEST_SECRET:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: environment

concurrency:
  group: ${{ github.workflow }}

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: ui-trusts
            browser: "edge"
            spec: |
              cypress/e2e/regression/trusts/**/*.cy.ts
          - group: ui-schools-and-general
            browser: "edge"
            spec: |
              cypress/e2e/regression/schools/**/*.cy.ts
              cypress/e2e/regression/navigation/**/*.cy.ts
              cypress/e2e/regression/*.cy.ts
          - group: a11y-comprehensive
            browser: "edge"
            spec: |
              cypress/e2e/accessibility/comprehensive-accessibility-audit.cy.ts
          - group: a11y-components
            browser: "edge"
            spec: |
              cypress/e2e/accessibility/components/**/*.cy.ts
    container:
      image: cypress/browsers:22.14.0@sha256:5fedacf2c6b1fab4f2d2d24a1cb2054af6d0103e0b163cd5064e523f45ca1a88
    defaults:
      run:
        working-directory: tests/DFE.FindInformationAcademiesTrusts.CypressTests
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Cypress environment
        run: |
          mkdir -p cypress/downloads
          mkdir -p cypress/accessibility
          mkdir -p cypress/accessibility/audit-reports
          mkdir -p cypress/screenshots
          chmod -R 755 cypress/

      - name: Run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_URL: ${{ secrets.BASE_URL }}
          CYPRESS_AUTH_KEY: ${{ secrets.TEST_OVERRIDE_CYPRESS_TEST_SECRET }}
        with:
          browser: ${{ matrix.browser }}
          spec: ${{ matrix.spec }}
          working-directory: tests/DFE.FindInformationAcademiesTrusts.CypressTests
          wait-on: ${{ secrets.BASE_URL }}

      - name: Upload screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: screenshots-${{ inputs.environment }}-${{ matrix.group }}
          path: tests/DFE.FindInformationAcademiesTrusts.CypressTests/cypress/screenshots

      - name: Generate report
        if: ${{ failure() }}
        run: |
          mkdir mochareports
          npm run generate:html:report

      - name: Upload report
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: reports-${{ inputs.environment }}-${{ matrix.group }}
          path: tests/DFE.FindInformationAcademiesTrusts.CypressTests/mochareports

      - name: Upload accessibility reports
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: a11y-reports-${{ inputs.environment }}-${{ matrix.group }}
          path: tests/DFE.FindInformationAcademiesTrusts.CypressTests/cypress/accessibility
          if-no-files-found: ${{ matrix.group == 'a11y-comprehensive' && 'error' || 'warn' }}
