name: Run smoke deployment tests
run-name: Deployment tests for '${{ inputs.environment }}' - `${{ inputs.branch-name }}`

on:
  workflow_call:
    inputs: 
      environment: 
        required: true
        type: string
      branch-name: 
        required: true
        type: string
env:
  NODE_VERSION: 18.13.0
jobs:
  playwright:
    name: Smoke deployment tests
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: tests/playwright
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        name: Set up Node.js
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: |
            DfE.FindInformationAcademiesTrusts/package-lock.json
            tests/playwright/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Pin Playwright cache key
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION="$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")"
          PIN_VERSION=${PLAYWRIGHT_VERSION}-`date +%Y-%m-%d`
          echo "PLAYWRIGHT_VERSION=$PIN_VERSION" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright deployment tests
        env:
          PLAYWRIGHT_BASEURL: ${{ secrets.BASE_URL }}
          TEST_USER_ACCOUNT_NAME: ${{ secrets.TEST_USER_ACCOUNT_NAME }}
          TEST_USER_ACCOUNT_PASSWORD: ${{ secrets.TEST_USER_ACCOUNT_PASSWORD }}
        run: npm run test:deployment

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: deployment-tests-playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 7
