name: Run automated UI tests
run-name: UI tests for '${{ inputs.environment }}' - `${{ inputs.branch-name }}`

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch-name:
        required: true
        type: string
    secrets:
      BASE_URL:
        required: true
      TEST_OVERRIDE_CYPRESS_TEST_SECRET:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: environment

concurrency:
  group: ${{ github.workflow }}

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        browser: [
          "edge"
        ]
    container:
      image: cypress/browsers:22.14.0
    defaults:
      run:
        working-directory: tests/DFE.FindInformationAcademiesTrusts.CypressTests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_URL: ${{ secrets.BASE_URL }}
          CYPRESS_AUTH_KEY: ${{ secrets.TEST_OVERRIDE_CYPRESS_TEST_SECRET }}
        with:
          browser: ${{ matrix.browser }}
          working-directory: tests/DFE.FindInformationAcademiesTrusts.CypressTests
          wait-on: ${{ secrets.BASE_URL }}

      - name: Upload screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ inputs.environment }}-${{ matrix.browser }}
          path: tests/DFE.FindInformationAcademiesTrusts.CypressTests/cypress/screenshots

      - name: Generate report
        if: ${{ failure() }}
        run: |
          mkdir mochareports
          npm run generate:html:report

      - name: Upload report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ inputs.environment }}-${{ matrix.browser }}
          path: tests/DFE.FindInformationAcademiesTrusts.CypressTests/mochareports
