name: Run smoke deployment tests
run-name: Deployment tests for '${{ inputs.environment }}' - `${{ inputs.branch-name }}`

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch-name:
        required: true
        type: string
env:
  NODE_VERSION: 18.13.0
  LAST_COMMIT_SHA: default

jobs:
  cypress-tests:
    name: Smoke deployment tests
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: tests/DFE.FindInformationAcademiesTrusts.CypressTests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set SHA environment variable
        run: |
          echo "LAST_COMMIT_SHA=${GITHUB_SHA:(-7)}" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        name: Set up Node.js
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: |
            DfE.FindInformationAcademiesTrusts/package-lock.json
            tests/DFE.FindInformationAcademiesTrusts.CypressTests/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run the cypress tests
        run: npm run cy:deployment -- --env url=${{ secrets.BASE_URL }},authKey=${{ secrets.TEST_OVERRIDE_CYPRESS_TEST_SECRET}}

      - name: Upload screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ inputs.environment }}
          path: tests/DFE.FindInformationAcademiesTrusts.CypressTests/cypress/screenshots
          
      - name: Generate report
        if: ${{ failure() }}
        run: |
          mkdir mochareports
          npm run generate:html:report

      - name: Upload report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ inputs.environment }}
          path: tests/DFE.FindInformationAcademiesTrusts.CypressTests/mochareports
