name: Run UI tests on isolated environment

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened]
  push:
    branches: [ main ]
env:
  NODE_VERSION: 18.13.0
jobs:
  playwright:
    name: Set up container and run tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tests/playwright
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        name: Set up Node.js
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: |
            DfE.FindInformationAcademiesTrusts/package-lock.json
            tests/playwright/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages[''].version)")" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Start services
        working-directory: ./docker
        run: docker compose -f docker-compose.ci.yml up -d

      - name: Run Playwright tests
        env:
          CI: true
          PLAYWRIGHT_BASEURL: "http://localhost"
          WIREMOCK_BASEURL: "http://localhost:8080"
        run: npm run test:ci

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 7

      - name: Stop services
        if: always()
        working-directory: ./docker
        run: docker compose -f docker-compose.ci.yml stop
