name: Run security scanner tests

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Deploy to environment"]
  #   types:
  #     - completed

env:
  ZAP_ADDRESS: localhost
  ZAP_PORT: 9876
  ZAP_API_KEY: 5c93eec3-b5c0-4252-9061-017ebff89450
  NODE_VERSION: 18.13.0
  LAST_COMMIT_SHA: default

jobs:
  run-tests-with-zap:
    name: Run Cypress tests with OWASP ZAP
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/DFE.FindInformationAcademiesTrusts.CypressTests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set SHA environment variable
        run: |
          echo "LAST_COMMIT_SHA=${GITHUB_SHA:(-7)}" >> $GITHUB_ENV

      - name: Create directory on runner
        run: |
          mkdir -m 777 ${{ github.workspace }}/zapoutput

      - name: Get latest ZAP container version
        run: |
          ZAP_VERSION="$(wget -q -O - "https://hub.docker.com/v2/repositories/softwaresecurityproject/zap-stable/tags?page_size=2" | grep -o '"name": *"[^"]*' | grep -o '[^"]*$' | tail -n 1)"
          echo "ZAP_VERSION=${ZAP_VERSION}">> $GITHUB_ENV

      - name: Restore ZAP container from cache if exists
        id: cache-docker-zap
        uses: actions/cache@v4
        with:
          path: ~/ci/cache/docker/softwaresecurityproject
          key: cache-docker-zap-${{ env.ZAP_VERSION }}

      - name: Use cached image if hit
        if: steps.cache-docker-zap.outputs.cache-hit == 'true'
        run: docker image load --input ~/ci/cache/docker/softwaresecurityproject/zap-stable-${{ env.ZAP_VERSION }}.tar

      - name: Pull image if no cache hit
        if: steps.cache-docker-zap.outputs.cache-hit != 'true'
        run: docker pull softwaresecurityproject/zap-stable:latest && mkdir -p ~/ci/cache/docker/softwaresecurityproject && docker image save softwaresecurityproject/zap-stable:latest --output ~/ci/cache/docker/softwaresecurityproject/zap-stable-${{ env.ZAP_VERSION }}.tar

      - name: Start ZAP container
        env:
          ZAP_PORT: 9876
        run: docker run --name zap_container --rm -d -v ${{ github.workspace }}/zapoutput/:/zap/wrk:rw -u zap -p ${{ env.ZAP_PORT }}:${{ env.ZAP_PORT }} -i softwaresecurityproject/zap-stable zap.sh -daemon -port ${{ env.ZAP_PORT }} -host 0.0.0.0 -config api.key=${{ env.ZAP_API_KEY }} -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config network.localServers.mainProxy.alpn.enabled=false -config network.localServers.mainProxy.address=0.0.0.0

      - uses: actions/setup-node@v4
        name: Set up Node.js
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: |
            DfE.FindInformationAcademiesTrusts/package-lock.json
            tests/DFE.FindInformationAcademiesTrusts.CypressTests/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run security tests
        env:
          CI: true
          BASE_URL: ${{ secrets.BASE_URL }}
          HTTP_PROXY: "http://${{ env.ZAP_ADDRESS }}:${{ env.ZAP_PORT }}"
          NO_PROXY: ".gvt1.com"
          ZAP: true
          ZAP_API_KEY: ${{ env.ZAP_API_KEY }}
          ZAP_ADDRESS: ${{ env.ZAP_ADDRESS }}
          ZAP_PORT: ${{ env.ZAP_PORT }}
        run: npm run cy:deployment -- --env url=${{ secrets.BASE_URL }},authKey=${{ secrets.TEST_OVERRIDE_CYPRESS_TEST_SECRET}}

      - name: Azure login with SPN
        if: '!cancelled()'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.OWASP_AZ_CREDENTIALS }}

      - name: Push report to blob storage
        if: '!cancelled()'
        uses: azure/CLI@v2
        with:
          azcliversion: 2.53.0
          inlineScript: |
            CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
            az storage blob upload \
              --container-name ${{ secrets.OWASP_STORAGE_CONTAINER_NAME }} \
              --account-name ${{ secrets.OWASP_STORAGE_ACCOUNT_NAME }} \
              --file "${{ github.workspace }}/zapoutput/ZAP-Report.html" \
              --name "Dfe.FindInformationAcademiesTrusts/$CHECKED_OUT_SHA/ZAP-Report.html" \
              --auth-mode login \
              --overwrite

      - name: Stop ZAP container
        if: always()
        run: docker stop zap_container
